# ---------------------------------------------------------------------------
# Global
# ---------------------------------------------------------------------------
variables:
  RELEASE_REGISTRY_IMAGE: index.docker.io/magentaaps/os2mo-ldap-import-export
  RELEASE_REGISTRY: docker.io
  IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  PYTEST_COV_MODULE: mo_ldap_import_export
  PYTEST_COV_FAIL_UNDER: 100
  PRECOMMIT_USE_POETRY: "true"

stages:
  - lint
  - test
  - coverage
  - build
  - release
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

include:
  # See https://git.magenta.dk/labs/salt-automation/-/tree/master/gitlab-ci-templates/common

    # Runs linting
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/pre-commit.v1.yml

    # Runs testing
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/python/pytest.v1.yml

  # Opdaterer automatisk med et nyt tag
  #- project: labs/salt-automation
  #  file: /gitlab-ci-templates/common/autopub.v1.yml

  # Includes til at køre config-updateren, se anvendelse længere nede
  #- project: labs/salt-automation
  #  file: /gitlab-ci-templates/common/config-updater-meta.v1.yml

  # Kører build
  - project: labs/salt-automation
    file: /gitlab-ci-templates/common/docker-build-meta.v1.yml

  # Kører automatisk release
  - project: labs/salt-automation
    file: /gitlab-ci-templates/common/docker-release.v1.yml


Build:
  extends:
    - .build-docker
  variables:
    CI_IMAGE: ${IMAGE_SHA}
    BUILD_DOCKER_EXTRA_FLAGS: --build-arg=COMMIT_SHA=${CI_COMMIT_SHA} --build-arg=COMMIT_TAG=${CI_COMMIT_TAG}



Release:
  extends: .release-default
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_REF_NAME == "54355_initial_image_release"
      when: on_success
    - when: never
  variables:
    MASTER_BRANCH_NAME: 54355_initial_image_release
    CI_IMAGE: ${IMAGE_SHA}
    RELEASE_IMAGE: ${RELEASE_REGISTRY_IMAGE}
  script:
    - skopeo copy
      --src-creds=${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
      --dest-creds=${RELEASE_REGISTRY_USER}:${RELEASE_REGISTRY_PASSWORD}
      "docker://${CI_IMAGE}"
      "docker://${RELEASE_IMAGE}:${MASTER_BRANCH_NAME}"


# Kører config-updater for test
#Deploy to Test:
#  extends: .release-to-test
#  needs: []
#  variables:
#    ENDPOINT: os2mo/flux/ldap_import_export/update-test

# Kører config-updater for prod
#Deploy to Prod:
#  extends: .release-to-prod
#  needs: []
#  variables:
#    ENDPOINT: os2mo/flux/ldap_import_export/update-prod

