# ---------------------------------------------------------------------------
# Global
# ---------------------------------------------------------------------------
variables:
  RELEASE_REGISTRY_IMAGE: index.docker.io/magentaaps/os2mo-ldap-import-export
  RELEASE_REGISTRY: docker.io
  IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  PYTEST_COV_MODULE: mo_ldap_import_export
  PYTEST_COV_FAIL_UNDER: 100
  PRECOMMIT_USE_POETRY: "true"

stages:
  - lint
  - test
  - coverage
  - build
  - release
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

include:
  # See https://git.magenta.dk/labs/salt-automation/-/tree/master/gitlab-ci-templates/common

    # Runs linting
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/pre-commit.v1.yml

    # Runs testing
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/python/pytest.v1.yml

  # Opdaterer automatisk med et nyt tag
  #- project: labs/salt-automation
  #  file: /gitlab-ci-templates/common/autopub.v1.yml

  # Includes til at køre config-updateren, se anvendelse længere nede
  #- project: labs/salt-automation
  #  file: /gitlab-ci-templates/common/config-updater-meta.v1.yml

  # Kører build
  - project: labs/salt-automation
    file: /gitlab-ci-templates/common/docker-build.v1.yml

  # Kører automatisk release
  - project: labs/salt-automation
    file: /gitlab-ci-templates/common/docker-release.v1.yml




# Kører config-updater for test
#Deploy to Test:
#  extends: .release-to-test
#  needs: []
#  variables:
#    ENDPOINT: os2mo/flux/ldap_import_export/update-test

# Kører config-updater for prod
#Deploy to Prod:
#  extends: .release-to-prod
#  needs: []
#  variables:
#    ENDPOINT: os2mo/flux/ldap_import_export/update-prod

