# SPDX-FileCopyrightText: 2022 Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        files: \.(ts|js|svelte|css|html)$

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.1.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
