version: "3"

services:

  mo_ldap_import_export:
    container_name: mo_ldap_ie
    build: .
    command: ["uvicorn", "--factory", "app.main:create_app", "--host", "0.0.0.0", "--reload", "--reload-include", "*.json"]

    env_file:
      ./dev-environment/mo_ldap_import_export.env
    environment:
      amqp_url: "amqp://guest:guest@msg_broker"

      AUTH_SERVER: "http://keycloak:8080/auth"

      MO_URL: "http://mo"
      CLIENT_ID: "dipex"
      CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"

    volumes:
      - ./mo_ldap_import_export:/opt/app/
    networks:
      - os2mo_default
    ports:
      - "8000:8000"

networks:
  os2mo_default:
    external: true

