version: "3"

services:

  mo_ldap_import_export:
    container_name: mo_ldap_ie
    build: .
    command: ["uvicorn", "--factory", "app.main:create_app", "--host", "0.0.0.0", "--reload"]

    environment:
      amqp_url: "amqp://guest:guest@msg_broker"

      LDAP_CONTROLLERS: '[{"host": "100.110.188.107"}]'
      LDAP_DOMAIN: "LDAP"
      LDAP_USER: ""
      LDAP_PASSWORD: ""
      LDAP_SEARCH_BASE: "DC=ad,DC=addev"
      LDAP_ORGANIZATIONAL_UNIT: "OU=Magenta"

      AUTH_SERVER: "http://keycloak:8080/auth"

      MO_URL: "http://mo"
      CLIENT_ID: "dipex"
      CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"

    volumes:
      - ./mo_ldap_import_export:/opt/app/
    networks:
      - os2mo_default
    ports:
      - "8000:8000"

networks:
  os2mo_default:
    external: true

