# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0
version: "3"
services:
  ldap:
    container_name: ldap
    image: osixia/openldap:1.5.0
    command: ["--copy-service", "--loglevel", "debug"]
    environment:
      LDAP_ORGANISATION: "magenta"
      LDAP_DOMAIN: "magenta.dk"
      LDAP_ADMIN_PASSWORD: "AdminPassword123"
      LDAP_CONFIG_PASSWORD: "ConfigPassword123"

      LDAP_LOG_LEVEL: 512
    volumes:
      - ./dev-environment/ldif/:/container/service/slapd/assets/config/bootstrap/ldif/custom/:ro
      - ./dev-environment/schema/:/container/service/slapd/assets/config/bootstrap/schema/custom/:ro
    networks:
      - default
#    ports:
#      - "389:389"

  mo-init:
    image: magentaaps/os2mo-init:5
    environment:
      MO_URL: "http://mo:5000"
      CLIENT_ID: "dipex"
      CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
      AUTH_SERVER: "http://keycloak:8080/auth"
      AUTH_REALM: "mo"
    volumes:
      - type: bind
        source: ./dev-environment/init.config.yaml
        target: /config/config.yml
        read_only: true
    restart: on-failure
    networks:
      - os2mo_default

  mo_ldap_import_export:
    container_name: mo_ldap_ie
    build: .
    command: ["uvicorn", "--factory", "mo_ldap_import_export.main:create_app", "--host", "0.0.0.0", "--reload"]
    environment:
      # MO
      FASTRAMQPI__AMQP__URL: "amqp://guest:guest@msg-broker"
      FASTRAMQPI__AUTH_SERVER: "http://keycloak:8080/auth"
      FASTRAMQPI__MO_URL: "http://mo:5000"
      FASTRAMQPI__CLIENT_ID: "dipex"
      FASTRAMQPI__CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
      FASTRAMQPI__DAP: "true"
      TZ: "Europe/Copenhagen"

      # Database
      FASTRAMQPI__DATABASE__USER: "fastramqpi"
      FASTRAMQPI__DATABASE__PASSWORD: "fastramqpi"
      FASTRAMQPI__DATABASE__HOST: "db"
      FASTRAMQPI__DATABASE__NAME: "fastramqpi"

      # LDAP
      LDAP_CONTROLLERS: '[{"host": "ldap"}]'
      LDAP_DOMAIN: "magenta.dk"
      LDAP_USER: "cn=admin,dc=magenta,dc=dk"
      LDAP_PASSWORD: "AdminPassword123"
      LDAP_SEARCH_BASE: "dc=magenta,dc=dk"
      LDAP_OUS_TO_SEARCH_IN: '["ou=os2mo,o=magenta"]'
      LDAP_OUS_TO_WRITE_TO: '[""]'
      LDAP_OU_FOR_NEW_USERS: "ou=os2mo,o=magenta"
      LDAP_DIALECT: "Standard"
      LDAP_AUTH_METHOD: "simple"

      PRODUCTION: False

      LISTEN_TO_CHANGES_IN_MO: True
      LISTEN_TO_CHANGES_IN_LDAP: True

      DEFAULT_ORG_UNIT_TYPE: "Afdeling"
      DEFAULT_ORG_UNIT_LEVEL: "N1"

      # Produced using: yq -o=json kolding_fixture.yaml
      # Followed by escaping the single quotes within templates

      CONVERSION_MAPPING: >-
        {
            "ldap_to_mo": {
                "Employee": {
                    "objectClass": "ramodels.mo.employee.Employee",
                    "_import_to_mo_": "false",
                    "uuid": "{{ employee_uuid or NONE }}",
                    "nickname_givenname": "{{ get_employee_dict(employee_uuid).nickname_givenname }}",
                    "nickname_surname": "{{ get_employee_dict(employee_uuid).nickname_surname }}",
                    "cpr_no": "{{ldap.employeeNumber|strip_non_digits or NONE}}",
                    "user_key": "{{ ldap.title }}",
                    "givenname": "{{ ldap.givenName }}",
                    "surname": "{{ ldap.sn }}"
                },
                "ADtitle": {
                    "objectClass": "ramodels.mo.details.it_system.ITUser",
                    "_import_to_mo_": "true",
                    "user_key": "{{ ldap.title }}",
                    "itsystem": "{{ dict(uuid=get_it_system_uuid('ADtitle')) }}",
                    "validity": "{{ dict(from_date=now()|mo_datestring) }}",
                    "person": "{{ dict(uuid=employee_uuid or NONE) }}"
                },
                "ADUUID": {
                    "objectClass": "ramodels.mo.details.it_system.ITUser",
                    "_import_to_mo_": "true",
                    "_terminate_": "{{ now()|mo_datestring if ldap.title == \"WOW\" else NONE }}",
                    "user_key": "{{ ldap.entryUUID }}",
                    "itsystem": "{{ dict(uuid=get_it_system_uuid('ADUUID')) }}",
                    "validity": "{{ dict(from_date=now()|mo_datestring) }}",
                    "person": "{{ dict(uuid=employee_uuid or NONE) }}"
                }
            },
            "mo_to_ldap": {
                "Employee": {
                    "objectClass": "inetOrgPerson",
                    "_export_to_ldap_": "true",
                    "employeeNumber": "{{mo_employee.cpr_no}}",
                    "title": "{{ mo_employee.user_key }}",
                    "givenName": "{{ mo_employee.givenname }}",
                    "sn": "{{ mo_employee.surname }}"
                },
                "ADtitle": {
                    "objectClass": "inetOrgPerson",
                    "_export_to_ldap_": "false",
                    "title": "{{ mo_employee_it_user.user_key }}",
                    "employeeNumber": "{{ mo_employee.cpr_no }}"
                },
                "ADUUID": {
                    "objectClass": "inetOrgPerson",
                    "_export_to_ldap_": "false",
                    "title": "{{ NONE }}",
                    "entryUUID": "{{ mo_employee_it_user.user_key }}",
                    "employeeNumber": "{{ mo_employee.cpr_no }}"
                }
            },
            "username_generator": {
                "objectClass": "UserNameGenerator",
                "combinations_to_try": ["FFFX", "LLLX"]
            }
        }

    volumes:
      - ./mo_ldap_import_export/:/app/mo_ldap_import_export:ro
      - ./tests/:/app/tests/:ro
    networks:
      - default
      - os2mo_default
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:5678:5678"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: "fastramqpi"
      POSTGRES_PASSWORD: "fastramqpi"
      POSTGRES_DB: "fastramqpi"
    networks:
      - default

networks:
  os2mo_default:
    external: true
