[tool.poetry]
name = "mo_ldap_import_export"
version = "0.0.0" # versioning handled by conventional commits
description = "Rammearkitektur AMQP service for making AMQP messages on changing effects in os2mo."
authors = ["Magenta ApS <info@magenta.dk>"]
license = "MPL-2.0"

[tool.poetry.dependencies]
python = "^3.10"
structlog = "^23.1.0"
ramqp = "^9.0.0"
fastramqpi = "^5.2.0"
pydantic = "^1.9.0"
raclients = "^3.3.2"
gql = "^3.5.0"
more-itertools = "^9.1.0"
ra-utils = "^1.14.0"
uvicorn = "^0.27.1"
prometheus-fastapi-instrumentator = "^5.8.1"
fastapi = ">=0.101"
ldap3 = "^2.9.1"
strawberry-graphql = "^0.219.1"
pandas = "^2.2.0"
fastapi-utils = "^0.2.1"
python-dotenv = "^1.0.1"
httpx = "^0.26.0"
# pycryptodome is needed due to https://github.com/cannatag/ldap3/issues/1051
pycryptodome = "^3.20.0"

[tool.poetry.group.pre-commit.dependencies]
mypy = "^1.8.0"
types-tqdm = "^4.66.0.20240106"
types-ldap3 = "^2.9.13.20240119"
types-pyyaml = "^6.0.12.12"
reorder-python-imports = "^3.12.0"
pre-commit = "^3.6.0"
pandas-stubs = "^2.1.4.231227"
ruff = "^0.2.1"

[tool.poetry.group.test.dependencies]
mergedeep = "^1.3.4"
pytest = "^7.4.3"
pytest-asyncio = "^0.19.0"
pytest-cov = "^4.1.0"
pytest-split = "^0.8.2"
pytest-xdist = "^3.5.0"


[tool.poetry.group.dev.dependencies]
debugpy = "^1.8.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode="auto"

[tool.mypy]
python_version = "3.10"
warn_return_any = "True"
warn_unused_configs = "True"
check_untyped_defs = "False"  # TODO: Turn on
disallow_untyped_defs = "False"  # TODO: Turn on
plugins = "pydantic.mypy"

[tool.flake8]
max-line-length = 999
exclude = [
    ".git", "__pycache__", ".mypy_cache", ".pytest_cache", ".venv", ".gitlab"
]
