[tool.poetry]
name = "mo_ldap_import_export"
version = "0.0.0" # versioning handled by conventional commits
description = "Rammearkitektur AMQP service for making AMQP messages on changing effects in os2mo."
authors = ["Magenta ApS <info@magenta.dk>"]
license = "MPL-2.0"

[tool.poetry.dependencies]
python = "^3.10"
structlog = "^23.1.0"
ramqp = "^9.0.0"
fastramqpi = "^1.5.4"
pydantic = "^1.9.0"
raclients = "3.3.2"
gql = "^3.2.0"
more-itertools = "^9.1.0"
ra-utils = "^1.0.0"
uvicorn = {extras = ["standard"], version = "^0.17.6"}
prometheus-fastapi-instrumentator = "^5.8.1"
fastapi = "^0.95.0"
pytest-asyncio = "^0.19.0"
pytest-cov = "^4.0.0"
pytest-split = "^0.8.1"
pytest-xdist = "^3.2.0"
ldap3 = "^2.9.1"
strawberry-graphql = "^0.116.4"
pycryptodome = "^3.9.8"
pandas = "^1.5.1"
fastapi-utils = "^0.2.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = "^22.3.0"
reorder-python-imports = "^3.1.0"
mypy = "^0.991"
pre-commit = "^2.19.0"
pylint-pydantic = "^0.1.4"
requests = "^2.28.0"
asgi-lifespan = "^1.0.1"

[tool.poetry.group.dev.dependencies]
mergedeep = "^1.3.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.autopub]
git-username = "MagentaBot"
git-email = "info@magenta.dk"

[tool.pytest.ini_options]
asyncio_mode="auto"

[tool.mypy]
python_version = "3.10"
warn_return_any = "True"
warn_unused_configs = "True"
check_untyped_defs = "False"  # TODO: Turn on
disallow_untyped_defs = "False"  # TODO: Turn on
plugins = "pydantic.mypy"

[tool.flake8]
max-line-length = 999
exclude = [
    ".git", "__pycache__", ".mypy_cache", ".pytest_cache", ".venv", ".gitlab"
]
