# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from collections import Counter
from collections.abc import Awaitable
from collections.abc import Callable
from functools import partial
from typing import Any
from typing import TypeAlias
from uuid import UUID

import pytest
from fastapi.encoders import jsonable_encoder
from fastramqpi.autogenerated_graphql_client import RAValidityInput
from fastramqpi.events import Event
from fastramqpi.pytest_util import retrying
from httpx import AsyncClient
from more_itertools import one

from mo_ldap_import_export.autogenerated_graphql_client import ClassCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import EmployeeCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import FacetCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client import ITSystemCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import OrganisationCreate
from mo_ldap_import_export.autogenerated_graphql_client import (
    OrganisationUnitCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client import RAOpenValidityInput
from mo_ldap_import_export.autogenerated_graphql_client import ValidityInput
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    EmployeeFilter,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ITSystemFilter,
)
from mo_ldap_import_export.depends import Settings
from mo_ldap_import_export.ldapapi import LDAPAPI
from mo_ldap_import_export.types import DN
from mo_ldap_import_export.types import LDAPUUID
from mo_ldap_import_export.types import EmployeeUUID
from mo_ldap_import_export.utils import combine_dn_strings

DN2UUID: TypeAlias = Callable[[DN], Awaitable[LDAPUUID]]
DNList2UUID: TypeAlias = Callable[[list[str]], Awaitable[LDAPUUID]]


@pytest.fixture
async def root_org(graphql_client: GraphQLClient) -> UUID:
    """Ensure the root organisation exists."""
    r = await graphql_client.org_create(
        input=OrganisationCreate(municipality_code=None)
    )
    return r.uuid


class AnyOrder(list):
    def __eq__(self, other):
        if isinstance(other, list):
            return Counter(self) == Counter(other)
        raise NotImplementedError("Only support lists")


@pytest.fixture
async def dn2uuid(ldap_api: LDAPAPI) -> DN2UUID:
    async def inner(dn: DN) -> LDAPUUID:
        return await ldap_api.get_ldap_unique_ldap_uuid(dn)

    return inner


@pytest.fixture
async def dnlist2uuid(dn2uuid: DN2UUID) -> DNList2UUID:
    async def inner(dnlist: list[str]) -> LDAPUUID:
        dn = combine_dn_strings(dnlist)
        return await dn2uuid(dn)

    return inner


@pytest.fixture
def ldap_suffix() -> list[str]:
    return ["dc=magenta", "dc=dk"]


@pytest.fixture
async def ldap_org(write_ldap_api: LDAPAPI, ldap_suffix: list[str]) -> list[str]:
    o_dn = ["o=magenta"] + ldap_suffix
    await write_ldap_api.ldap_connection.ldap_add(
        combine_dn_strings(o_dn),
        object_class=["top", "organization"],
        attributes={"objectClass": ["top", "organization"], "o": "magenta"},
    )
    return o_dn


@pytest.fixture
async def ldap_org_unit(write_ldap_api: LDAPAPI, ldap_org: list[str]) -> list[str]:
    ou_dn = ["ou=os2mo"] + ldap_org
    await write_ldap_api.ldap_connection.ldap_add(
        combine_dn_strings(ou_dn),
        object_class=["top", "organizationalUnit"],
        attributes={"objectClass": ["top", "organizationalUnit"], "ou": "os2mo"},
    )
    return ou_dn


@pytest.fixture
async def ldap_org_unit_uuid(
    ldap_org_unit: list[str], dnlist2uuid: DNList2UUID
) -> UUID:
    return await dnlist2uuid(ldap_org_unit)


AddLdapPerson: TypeAlias = Callable[[str, str], Awaitable[list[str]]]


@pytest.fixture
async def add_ldap_person(
    write_ldap_api: LDAPAPI, ldap_org_unit: list[str]
) -> AddLdapPerson:
    async def adder(identifier: str, cpr_number: str) -> list[str]:
        person_dn = ["uid=" + identifier] + ldap_org_unit
        await write_ldap_api.ldap_connection.ldap_add(
            combine_dn_strings(person_dn),
            object_class=["top", "person", "organizationalPerson", "inetOrgPerson"],
            attributes={
                "objectClass": [
                    "top",
                    "person",
                    "organizationalPerson",
                    "inetOrgPerson",
                ],
                "uid": identifier,
                "cn": "cn",
                "givenName": "givenName",
                "sn": "sn",
                "ou": "os2mo",
                "mail": identifier + "@ad.kolding.dk",
                "userPassword": "{SSHA}j3lBh1Seqe4rqF1+NuWmjhvtAni1JC5A",
                "employeeNumber": cpr_number,
                "title": "title",
            },
        )
        return person_dn

    return adder


@pytest.fixture
async def ldap_person(write_ldap_api: LDAPAPI, ldap_org_unit: list[str]) -> list[str]:
    person_dn = ["uid=abk"] + ldap_org_unit
    await write_ldap_api.ldap_connection.ldap_add(
        combine_dn_strings(person_dn),
        object_class=["top", "person", "organizationalPerson", "inetOrgPerson"],
        attributes={
            "objectClass": ["top", "person", "organizationalPerson", "inetOrgPerson"],
            "uid": "abk",
            "cn": "Aage Bach Klarskov",
            "givenName": "Aage",
            "sn": "Bach Klarskov",
            "ou": "os2mo",
            "mail": "abk@ad.kolding.dk",
            "userPassword": "{SSHA}j3lBh1Seqe4rqF1+NuWmjhvtAni1JC5A",
            "employeeNumber": "2108613133",
            "title": "Skole underviser",
        },
    )
    return person_dn


@pytest.fixture
async def ldap_person_uuid(ldap_person: list[str], dnlist2uuid: DNList2UUID) -> UUID:
    return await dnlist2uuid(ldap_person)


@pytest.fixture
async def ldap_person_dn(ldap_person: list[str]) -> DN:
    return combine_dn_strings(ldap_person)


@pytest.fixture
async def mo_person(graphql_client: GraphQLClient) -> UUID:
    r = await graphql_client.person_create(
        input=EmployeeCreateInput(
            given_name="Aage",
            surname="Bach Klarskov",
            cpr_number="2108613133",
        )
    )
    return r.uuid


SEED_VALIDITY = ValidityInput(from_="1930-01-01T00:00:00Z")
SEED_OPEN_VALIDITY = RAOpenValidityInput(from_="1930-01-01T00:00:00Z")


# --- Facet fixtures ---


async def _create_facet(graphql_client: GraphQLClient, user_key: str) -> UUID:
    r = await graphql_client.facet_create(
        input=FacetCreateInput(user_key=user_key, validity=SEED_VALIDITY)
    )
    return r.uuid


@pytest.fixture
async def org_unit_address_type_facet(
    root_org: UUID, graphql_client: GraphQLClient
) -> UUID:
    return await _create_facet(graphql_client, "org_unit_address_type")


@pytest.fixture
async def employee_address_type_facet(
    root_org: UUID, graphql_client: GraphQLClient
) -> UUID:
    return await _create_facet(graphql_client, "employee_address_type")


@pytest.fixture
async def leave_type_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "leave_type")


@pytest.fixture
async def visibility_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "visibility")


@pytest.fixture
async def engagement_job_function_facet(
    root_org: UUID, graphql_client: GraphQLClient
) -> UUID:
    return await _create_facet(graphql_client, "engagement_job_function")


@pytest.fixture
async def org_unit_type_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "org_unit_type")


@pytest.fixture
async def org_unit_level_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "org_unit_level")


@pytest.fixture
async def engagement_type_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "engagement_type")


@pytest.fixture
async def primary_type_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "primary_type")


@pytest.fixture
async def role_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "role")


# --- Class fixtures ---


async def _create_class(
    graphql_client: GraphQLClient,
    facet_uuid: UUID,
    class_user_key: str,
    name: str,
    scope: str,
) -> UUID:
    r = await graphql_client.class_create(
        input=ClassCreateInput(
            user_key=class_user_key,
            name=name,
            facet_uuid=facet_uuid,
            scope=scope,
            validity=SEED_VALIDITY,
        )
    )
    return r.uuid


@pytest.fixture
async def phone_unit(
    graphql_client: GraphQLClient, org_unit_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, org_unit_address_type_facet, "PhoneUnit", "Telefon", "PHONE"
    )


@pytest.fixture
async def email_unit(
    graphql_client: GraphQLClient, org_unit_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, org_unit_address_type_facet, "EmailUnit", "Email", "EMAIL"
    )


@pytest.fixture
async def phone_employee(
    graphql_client: GraphQLClient, employee_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, employee_address_type_facet, "PhoneEmployee", "Telefon", "PHONE"
    )


@pytest.fixture
async def adresse_post_employee(
    graphql_client: GraphQLClient, employee_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client,
        employee_address_type_facet,
        "AdressePostEmployee",
        "Postadresse",
        "DAR",
    )


@pytest.fixture
async def email_employee(
    graphql_client: GraphQLClient, employee_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, employee_address_type_facet, "EmailEmployee", "Email", "EMAIL"
    )


@pytest.fixture
async def string_employee_address_type(
    graphql_client: GraphQLClient, employee_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client,
        employee_address_type_facet,
        "StringEmployee",
        "String Address",
        "TEXT",
    )


@pytest.fixture
async def orlov(graphql_client: GraphQLClient, leave_type_facet: UUID) -> UUID:
    return await _create_class(
        graphql_client, leave_type_facet, "Orlov", "Orlov", "TEXT"
    )


@pytest.fixture
async def intern(graphql_client: GraphQLClient, visibility_facet: UUID) -> UUID:
    return await _create_class(
        graphql_client, visibility_facet, "Intern", "Må vises internt", "INTERNAL"
    )


@pytest.fixture
async def public(graphql_client: GraphQLClient, visibility_facet: UUID) -> UUID:
    return await _create_class(
        graphql_client, visibility_facet, "Public", "Må vises eksternt", "PUBLIC"
    )


@pytest.fixture
async def secret(graphql_client: GraphQLClient, visibility_facet: UUID) -> UUID:
    return await _create_class(
        graphql_client, visibility_facet, "Secret", "Hemmelig", "SECRET"
    )


@pytest.fixture
async def jurist(
    graphql_client: GraphQLClient, engagement_job_function_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, engagement_job_function_facet, "Jurist", "Jurist", "TEXT"
    )


@pytest.fixture
async def afdeling(graphql_client: GraphQLClient, org_unit_type_facet: UUID) -> UUID:
    return await _create_class(
        graphql_client, org_unit_type_facet, "Afdeling", "Afdeling", "TEXT"
    )


@pytest.fixture
async def n1(graphql_client: GraphQLClient, org_unit_level_facet: UUID) -> UUID:
    return await _create_class(graphql_client, org_unit_level_facet, "N1", "N1", "TEXT")


@pytest.fixture
async def ansat(graphql_client: GraphQLClient, engagement_type_facet: UUID) -> UUID:
    return await _create_class(
        graphql_client, engagement_type_facet, "Ansat", "Ansat", "TEXT"
    )


@pytest.fixture
async def praktikant(
    graphql_client: GraphQLClient, engagement_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, engagement_type_facet, "Praktikant", "Praktikant", "TEXT"
    )


@pytest.fixture
async def primary(graphql_client: GraphQLClient, primary_type_facet: UUID) -> UUID:
    return await _create_class(
        graphql_client, primary_type_facet, "primary", "Primær", "3000"
    )


@pytest.fixture
async def non_primary(graphql_client: GraphQLClient, primary_type_facet: UUID) -> UUID:
    return await _create_class(
        graphql_client,
        primary_type_facet,
        "non-primary",
        "Ikke-primær ansættelse",
        "0",
    )


@pytest.fixture
async def explicitly_primary(
    graphql_client: GraphQLClient, primary_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client,
        primary_type_facet,
        "explicitly-primary",
        "Manuelt primær ansættelse",
        "5000",
    )


# --- IT system fixtures ---


async def _create_itsystem(
    graphql_client: GraphQLClient, user_key: str, name: str
) -> UUID:
    r = await graphql_client.itsystem_create(
        input=ITSystemCreateInput(
            user_key=user_key, name=name, validity=SEED_OPEN_VALIDITY
        )
    )
    return r.uuid


@pytest.fixture
async def aduuid(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_itsystem(graphql_client, "ADUUID", "Active Directory UUID")


@pytest.fixture
async def adtitle(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_itsystem(graphql_client, "ADtitle", "Active Directory Title")


# --- Seed fixture (pulls in all of the above) ---


@pytest.fixture
async def seed_mo_db(
    # TODO: Eliminate this fixture by having tests declare their own dependencies.
    #  Once no implicit dependencies remain, remove seed_mo_db from the
    #  pytest_collection_modifyitems hook in tests/conftest.py.
    # Ensure database is clean before seeding
    empty_db: None,
    # Classes (transitively pull in their facet fixtures and root_org)
    phone_unit: UUID,
    email_unit: UUID,
    phone_employee: UUID,
    adresse_post_employee: UUID,
    email_employee: UUID,
    string_employee_address_type: UUID,
    orlov: UUID,
    intern: UUID,
    public: UUID,
    secret: UUID,
    jurist: UUID,
    afdeling: UUID,
    n1: UUID,
    ansat: UUID,
    praktikant: UUID,
    primary: UUID,
    non_primary: UUID,
    explicitly_primary: UUID,
    # Facets without classes
    role_facet: UUID,
    # IT systems
    aduuid: UUID,
    adtitle: UUID,
) -> None:
    """Recreate all facets, classes, and IT systems from init.config.yaml."""


@pytest.fixture
async def mo_org_unit(graphql_client: GraphQLClient, afdeling: UUID) -> UUID:
    r = await graphql_client.org_unit_create(
        input=OrganisationUnitCreateInput(
            user_key="os2mo",
            name="os2mo",
            parent=None,
            org_unit_type=afdeling,
            validity=RAValidityInput(from_="1960-01-01T00:00:00Z"),
        )
    )
    return r.uuid


@pytest.fixture
async def read_itsystem_by_user_key(
    graphql_client: GraphQLClient,
) -> Callable[[str], Awaitable[UUID]]:
    async def inner(user_key: str) -> UUID:
        return one(
            (
                await graphql_client.read_itsystem_uuid(
                    ITSystemFilter(user_keys=[user_key])
                )
            ).objects
        ).uuid

    return inner


@pytest.fixture
async def trigger_sync(
    test_client: AsyncClient,
) -> Callable[[EmployeeUUID], Awaitable[None]]:
    async def inner(uuid: EmployeeUUID) -> None:
        result = await test_client.post(
            "/mo2ldap/person", json={"subject": str(uuid), "priority": 1}
        )
        assert result.status_code == 200, result.text

    return inner


@pytest.fixture
async def trigger_ldap_sync(
    test_client: AsyncClient,
) -> Callable[[LDAPUUID], Awaitable[None]]:
    async def inner(uuid: LDAPUUID) -> None:
        result = await test_client.post(
            "/ldap2mo/uuid", json={"subject": str(uuid), "priority": 1}
        )
        assert result.status_code == 200, result.text

    return inner


@pytest.fixture
async def trigger_mo_person(
    trigger_sync: Callable[[EmployeeUUID], Awaitable[None]],
    mo_person: EmployeeUUID,
) -> Callable[[], Awaitable[None]]:
    return partial(trigger_sync, mo_person)


@pytest.fixture
async def trigger_ldap_person(
    trigger_ldap_sync: Callable[[LDAPUUID], Awaitable[None]],
    ldap_person_uuid: LDAPUUID,
) -> Callable[[], Awaitable[None]]:
    return partial(trigger_ldap_sync, ldap_person_uuid)


@pytest.fixture
async def assert_mo_person(
    mo_person: UUID, graphql_client: GraphQLClient
) -> Callable[[dict[str, Any]], Awaitable[None]]:
    async def assert_employee(expected: dict[str, Any]) -> None:
        async for attempt in retrying():
            with attempt:
                employees = await graphql_client._testing__employee_read(
                    filter=EmployeeFilter(uuids=[mo_person])
                )
                employee = one(employees.objects)
                validities = [validity.dict() for validity in employee.validities]
                assert validities == [expected]

    return assert_employee


@pytest.fixture
async def assert_ldap_person(
    ldap_person_uuid: LDAPUUID,
    ldap_org_unit: list[str],
    ldap_api: LDAPAPI,
) -> Callable[[dict[str, Any]], Awaitable[None]]:
    settings = Settings()

    async def assert_employee(expected: dict[str, Any]) -> None:
        async for attempt in retrying():
            with attempt:
                response, _ = await ldap_api.ldap_connection.ldap_search(
                    search_base=combine_dn_strings(ldap_org_unit),
                    search_filter=f"({settings.ldap_unique_id_field}={ldap_person_uuid})",
                    attributes=[
                        "employeeNumber",
                        "carLicense",
                        "uid",
                        "cn",
                        "sn",
                        "givenName",
                        "displayName",
                    ],
                )
                employee = one(response)
                assert employee["attributes"] == expected

    return assert_employee


@pytest.fixture
async def trigger_mo_to_ldap_sync(
    test_client: AsyncClient,
) -> Callable[[str, UUID], Awaitable[None]]:
    async def inner(identifier: str, uuid: UUID) -> None:
        result = await test_client.post(
            f"/mo_to_ldap/{identifier}",
            json=jsonable_encoder(Event(subject=uuid, priority=10)),
        )
        assert result.status_code == 200, result.text

    return inner
