# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from uuid import UUID

import pytest
from httpx import AsyncClient
from more_itertools import one

from mo_ldap_import_export.autogenerated_graphql_client import EmployeeFilter
from mo_ldap_import_export.autogenerated_graphql_client import EngagementCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client import RAValidityInput
from mo_ldap_import_export.types import LDAPUUID


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo": {
                    "Employee": {
                        "objectClass": "Employee",
                        "_import_to_mo_": "true",
                        "_ldap_attributes_": ["sn", "employeeNumber"],
                        "uuid": "{{ employee_uuid or '' }}",
                        "given_name": "{{ requeue_if_none(load_mo_primary_engagement(employee_uuid)).user_key }}",
                        "surname": "{{ ldap.sn }}",
                        "cpr_number": "{{ ldap.employeeNumber }}",
                    },
                },
            }
        ),
    }
)
@pytest.mark.usefixtures("test_client")
async def test_to_mo_requeue_if_none(
    graphql_client: GraphQLClient,
    test_client: AsyncClient,
    ldap_person_uuid: LDAPUUID,
    mo_person: UUID,
    mo_org_unit: UUID,
    ansat: UUID,
    jurist: UUID,
    primary: UUID,
) -> None:
    async def get_given_name() -> str | None:
        employees = await graphql_client._testing__employee_read(
            filter=EmployeeFilter(uuids=[mo_person])
        )
        return one(one(employees.objects).validities).given_name

    payload = {"subject": str(ldap_person_uuid), "priority": 1}

    # No engagement in MO -> the given_name field requeues, yielding 409 (requeue)
    response = await test_client.post("/ldap2mo/uuid", json=payload)
    assert response.status_code == 409, response.text
    assert "Requeueing: Object is None" in response.text
    # Name is not updated
    assert await get_given_name() == "Aage"

    # Create the primary engagement that the template depends on
    engagement_user_key = "my-engagement"
    await graphql_client.engagement_create(
        input=EngagementCreateInput(
            user_key=engagement_user_key,
            person=mo_person,
            org_unit=mo_org_unit,
            engagement_type=ansat,
            job_function=jurist,
            primary=primary,
            validity=RAValidityInput(from_="2001-02-03T04:05:06Z"),
        )
    )

    # Same sync now succeeds, picking up the engagement's user_key
    response = await test_client.post("/ldap2mo/uuid", json=payload)
    assert response.status_code == 200, response.text
    assert await get_given_name() == engagement_user_key
