# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from datetime import datetime
from typing import Any
from uuid import UUID

import pytest
from httpx import AsyncClient
from more_itertools import one

from mo_ldap_import_export.autogenerated_graphql_client import AddressCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import AddressFilter
from mo_ldap_import_export.autogenerated_graphql_client import EmployeeFilter
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client import RAValidityInput
from mo_ldap_import_export.ldapapi import LDAPAPI
from mo_ldap_import_export.types import LDAPUUID
from mo_ldap_import_export.utils import MO_TZ
from mo_ldap_import_export.utils import mo_today


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo": {
                    "EmailEmployee": {
                        "objectClass": "Address",
                        "_import_to_mo_": "true",
                        "_ldap_attributes_": [],
                        "uuid": "{{ get_address_uuid({'address_type': {'user_key': 'EmailEmployee'}, 'employee': {'uuids': [employee_uuid]}}) }}",
                        "user_key": "-",
                        "value": "new@example.org",
                        "address_type": "{{ get_employee_address_type_uuid('EmailEmployee') }}",
                        "person": "{{ employee_uuid }}",
                    },
                },
            }
        ),
    }
)
@pytest.mark.usefixtures("test_client")
async def test_to_mo(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    mo_person: UUID,
    email_employee: UUID,
    ldap_api: LDAPAPI,
    ldap_person_uuid: LDAPUUID,
) -> None:
    async def get_address() -> list[dict[str, Any]]:
        addresses = await graphql_client._testing__address_read(
            filter=AddressFilter(
                employee=EmployeeFilter(uuids=[mo_person]),
                from_date=None,
                to_date=None,
            ),
        )
        address = one(addresses.objects)
        return [v.dict() for v in address.validities]

    # Create address in mo from some time in the past
    address = await graphql_client.address_create(
        input=AddressCreateInput(
            user_key="-",
            person=mo_person,
            address_type=email_employee,
            value="old@example.org",
            validity=RAValidityInput(
                from_=datetime(2020, 1, 1),
                to=None,
            ),
        )
    )

    assert await get_address() == [
        {
            "uuid": address.uuid,
            "user_key": "-",
            "person": [{"uuid": mo_person}],
            "address_type": {"user_key": "EmailEmployee"},
            "value": "old@example.org",
            "value2": None,
            "visibility": None,
            "validity": {
                "from_": datetime(2020, 1, 1, 0, 0, tzinfo=MO_TZ),
                "to": None,
            },
        },
    ]

    # Trigger sync
    result = await test_client.post(
        "/ldap2mo/uuid", json={"subject": str(ldap_person_uuid), "priority": 1}
    )
    assert result.status_code == 200, result.text

    assert await get_address() == [
        {
            "uuid": address.uuid,
            "user_key": "-",
            "person": [{"uuid": mo_person}],
            "address_type": {"user_key": "EmailEmployee"},
            "value": "old@example.org",
            "value2": None,
            "visibility": None,
            "validity": {
                "from_": datetime(2020, 1, 1, 0, 0, tzinfo=MO_TZ),
                "to": mo_today(),
            },
        },
        {
            "uuid": address.uuid,
            "user_key": "-",
            "person": [{"uuid": mo_person}],
            "address_type": {"user_key": "EmailEmployee"},
            "value": "new@example.org",
            "value2": None,
            "visibility": None,
            "validity": {
                "from_": mo_today(),
                "to": None,
            },
        },
    ]
