# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from collections.abc import Awaitable
from collections.abc import Callable
from uuid import UUID

import pytest
from more_itertools import one

from mo_ldap_import_export.autogenerated_graphql_client import EmployeeFilter
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client import ITUserFilter
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ITSystemFilter,
)
from mo_ldap_import_export.ldapapi import LDAPAPI
from mo_ldap_import_export.types import LDAPUUID
from mo_ldap_import_export.utils import combine_dn_strings
from tests.integration.conftest import AddEngagement
from tests.integration.conftest import AddLdapPerson


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo_any": {
                    "inetOrgPerson": [
                        {
                            "objectClass": "ITUser",
                            "_import_to_mo_": "true",
                            "_ldap_attributes_": [
                                "entryUUID",
                                "uid",
                                "carLicense",
                                "employeeNumber",
                            ],
                            "uuid": """
                            {{
                                get_ituser_uuid({
                                    'itsystem': {'user_keys': ['ADUUID']},
                                    'external_ids': [ldap.entryUUID|string]})
                            }}
                            """,
                            "external_id": "{{ ldap.entryUUID }}",
                            "user_key": "{{ ldap.uid }}",
                            "person": "{{ get_person_uuid({'cpr_numbers': [ldap.employeeNumber]}) }}",
                            "itsystem": "{{ get_it_system_uuid('ADUUID') }}",
                            "engagements": """
                                {%- set employee_uuid = get_person_uuid({'cpr_numbers': [ldap.employeeNumber]}) -%}
                                {%- if ldap.carLicense -%}
                                    {%- set selected = [get_engagement_uuid({'user_keys': [ldap.carLicense], 'employee': {'uuids': [employee_uuid]}})] -%}
                                {%- else -%}
                                    {%- set used = get_ldap_attribute_values_by_cpr(ldap.employeeNumber, 'carLicense') -%}
                                    {%- set all_engagements = get_engagement_uuids({'employee': {'uuids': [employee_uuid]}}) -%}
                                    {%- set used_engagements = get_engagement_uuids({'employee': {'uuids': [employee_uuid]}, 'user_keys': used}) -%}
                                    {%- set selected = all_engagements - used_engagements -%}
                                {%- endif -%}
                                {{ selected | map('string') | list | tojson }}
                            """,
                        },
                    ]
                },
            }
        ),
    }
)
async def test_ituser_engagement_assignment(
    graphql_client: GraphQLClient,
    mo_person: UUID,
    ldap_api: LDAPAPI,
    add_ldap_person: AddLdapPerson,
    add_engagement: AddEngagement,
    trigger_ldap_sync: Callable[[LDAPUUID], Awaitable[None]],
) -> None:
    cpr = "2108613133"

    # Create 4 engagements with different user-keys
    engagement_uuids = {
        user_key: await add_engagement(user_key)
        for user_key in ["eng1", "eng2", "eng3", "eng4"]
    }

    # Create 3 LDAP accounts for the same employee.
    # acc1 + acc2 have carLicense referencing an engagement user-key; acc3 does not.
    acc1_dn = combine_dn_strings(await add_ldap_person("acc1", cpr))
    await ldap_api.ldap_connection.ldap_modify(
        dn=acc1_dn, changes={"carLicense": [("MODIFY_ADD", "eng1")]}
    )
    acc1_uuid = await ldap_api.get_ldap_unique_ldap_uuid(acc1_dn)

    acc2_dn = combine_dn_strings(await add_ldap_person("acc2", cpr))
    await ldap_api.ldap_connection.ldap_modify(
        dn=acc2_dn, changes={"carLicense": [("MODIFY_ADD", "eng2")]}
    )
    acc2_uuid = await ldap_api.get_ldap_unique_ldap_uuid(acc2_dn)

    acc3_dn = combine_dn_strings(await add_ldap_person("acc3", cpr))
    acc3_uuid = await ldap_api.get_ldap_unique_ldap_uuid(acc3_dn)

    # Synchronize each LDAP account
    await trigger_ldap_sync(acc1_uuid)
    await trigger_ldap_sync(acc2_uuid)
    await trigger_ldap_sync(acc3_uuid)

    # Read all IT-users on the ADUUID IT system for the employee
    result = await graphql_client.read_filtered_itusers(
        filter=ITUserFilter(
            itsystem=ITSystemFilter(user_keys=["ADUUID"]),
            employee=EmployeeFilter(uuids=[mo_person]),
            from_date=None,
            to_date=None,
        )
    )
    ituser_uuids = [one(obj.validities).uuid for obj in result.objects]
    full = await graphql_client.read_itusers(uuids=ituser_uuids)
    itusers = [
        {
            "user_key": validity.user_key,
            "external_id": validity.external_id,
            "engagement_uuids": set(validity.engagement_uuids),
        }
        for obj in full.objects
        for validity in obj.validities
    ]
    assert len(itusers) == 3
    by_user_key = {ituser["user_key"]: ituser for ituser in itusers}
    ituser1 = by_user_key["acc1"]
    ituser2 = by_user_key["acc2"]
    ituser3 = by_user_key["acc3"]

    # Account 1: carLicense=eng1 -> engagement[eng1]
    assert ituser1["external_id"] == str(acc1_uuid)
    assert ituser1["engagement_uuids"] == {engagement_uuids["eng1"]}

    # Account 2: carLicense=eng2 -> engagement[eng2]
    assert ituser2["external_id"] == str(acc2_uuid)
    assert ituser2["engagement_uuids"] == {engagement_uuids["eng2"]}

    # Account 3: no carLicense -> the engagements not used by acc1/acc2
    assert ituser3["external_id"] == str(acc3_uuid)
    assert ituser3["engagement_uuids"] == {
        engagement_uuids["eng3"],
        engagement_uuids["eng4"],
    }
