# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from uuid import UUID
from uuid import uuid4

import pytest

from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ClassCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ITSystemCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    RAOpenValidityInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import ValidityInput
from mo_ldap_import_export.environments.main import itsystem_uuid_to_role_uuids


@pytest.fixture
async def itsystem(graphql_client: GraphQLClient) -> UUID:
    itsystem = await graphql_client.itsystem_create(
        input=ITSystemCreateInput(
            user_key="borgerpc",
            name="BorgerPC",
            validity=RAOpenValidityInput(from_="1970-01-01T00:00:00Z"),
        )
    )
    return itsystem.uuid


@pytest.mark.integration_test
async def test_no_itsystem(
    graphql_client: GraphQLClient,
) -> None:
    result = await itsystem_uuid_to_role_uuids(graphql_client, uuid4())
    assert result == set()


@pytest.mark.integration_test
@pytest.mark.parametrize(
    "validity",
    [
        # past
        RAOpenValidityInput(from_="1970-01-01T00:00:00Z", to="1980-01-01T00:00:00Z"),
        # present
        RAOpenValidityInput(from_="1970-01-01T00:00:00Z"),
        # future
        RAOpenValidityInput(from_="3000-01-01T00:00:00Z"),
    ],
)
async def test_no_role_itsystem(
    graphql_client: GraphQLClient,
    validity: RAOpenValidityInput,
) -> None:
    itsystem = await graphql_client.itsystem_create(
        input=ITSystemCreateInput(
            user_key="borgerpc", name="BorgerPC", validity=validity
        )
    )
    result = await itsystem_uuid_to_role_uuids(graphql_client, itsystem.uuid)
    assert result == set()


@pytest.mark.integration_test
@pytest.mark.parametrize(
    "validity",
    [
        # past
        ValidityInput(from_="1970-01-01T00:00:00Z", to="1980-01-01T00:00:00Z"),
        # future
        ValidityInput(from_="3000-01-01T00:00:00Z"),
    ],
)
async def test_past_and_future_role_itsystem(
    graphql_client: GraphQLClient,
    role_facet: UUID,
    itsystem: UUID,
    validity: ValidityInput,
) -> None:
    await graphql_client.class_create(
        input=ClassCreateInput(
            name="admin",
            user_key="admin",
            scope="TEXT",
            facet_uuid=role_facet,
            it_system_uuid=itsystem,
            validity=validity,
        )
    )
    result = await itsystem_uuid_to_role_uuids(graphql_client, itsystem)
    assert result == set()


@pytest.mark.integration_test
async def test_present_role_itsystem(
    graphql_client: GraphQLClient,
    role_facet: UUID,
    itsystem: UUID,
) -> None:
    role = await graphql_client.class_create(
        input=ClassCreateInput(
            name="admin",
            user_key="admin",
            scope="TEXT",
            facet_uuid=role_facet,
            it_system_uuid=itsystem,
            validity=ValidityInput(from_="1970-01-01T00:00:00Z"),
        )
    )
    result = await itsystem_uuid_to_role_uuids(graphql_client, itsystem)
    assert result == {role.uuid}


@pytest.mark.integration_test
@pytest.mark.parametrize(
    "validity1,validity2,expected",
    [
        # Both past
        (
            ValidityInput(from_="1970-01-01T00:00:00Z", to="1980-01-01T00:00:00Z"),
            ValidityInput(from_="1970-01-01T00:00:00Z", to="1980-01-01T00:00:00Z"),
            set(),
        ),
        # Both present
        (
            ValidityInput(from_="1970-01-01T00:00:00Z"),
            ValidityInput(from_="1970-01-01T00:00:00Z"),
            {1, 2},
        ),
        # Both future
        (
            ValidityInput(from_="3000-01-01T00:00:00Z"),
            ValidityInput(from_="3000-01-01T00:00:00Z"),
            set(),
        ),
        # One past, one present
        (
            ValidityInput(from_="1970-01-01T00:00:00Z", to="1980-01-01T00:00:00Z"),
            ValidityInput(from_="1970-01-01T00:00:00Z"),
            {2},
        ),
        # One past, one present, flipped
        (
            ValidityInput(from_="1970-01-01T00:00:00Z"),
            ValidityInput(from_="1970-01-01T00:00:00Z", to="1980-01-01T00:00:00Z"),
            {1},
        ),
        # One past, one future
        (
            ValidityInput(from_="1970-01-01T00:00:00Z", to="1980-01-01T00:00:00Z"),
            ValidityInput(from_="3000-01-01T00:00:00Z"),
            set(),
        ),
    ],
)
async def test_present_multiple_roles_itsystem(
    graphql_client: GraphQLClient,
    role_facet: UUID,
    itsystem: UUID,
    validity1: ValidityInput,
    validity2: ValidityInput,
    expected: set[int],
) -> None:
    expected_set = set()

    role1 = await graphql_client.class_create(
        input=ClassCreateInput(
            name="admin",
            user_key="admin",
            scope="TEXT",
            facet_uuid=role_facet,
            it_system_uuid=itsystem,
            validity=validity1,
        )
    )
    if 1 in expected:
        expected_set.add(role1.uuid)

    role2 = await graphql_client.class_create(
        input=ClassCreateInput(
            name="admin",
            user_key="admin",
            scope="TEXT",
            facet_uuid=role_facet,
            it_system_uuid=itsystem,
            validity=validity2,
        )
    )
    if 2 in expected:
        expected_set.add(role2.uuid)

    result = await itsystem_uuid_to_role_uuids(graphql_client, itsystem)
    assert result == expected_set
