# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0
import json
from datetime import datetime
from unittest.mock import ANY
from uuid import UUID

import pytest
from freezegun import freeze_time
from httpx import AsyncClient
from ldap3 import Connection
from more_itertools import last
from more_itertools import one

from mo_ldap_import_export.autogenerated_graphql_client import AddressFilter
from mo_ldap_import_export.autogenerated_graphql_client import EmployeeFilter
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.ldap import ldap_add
from mo_ldap_import_export.ldap import ldap_modify
from mo_ldap_import_export.ldapapi import LDAPAPI
from mo_ldap_import_export.utils import MO_TZ
from mo_ldap_import_export.utils import combine_dn_strings
from mo_ldap_import_export.utils import mo_today


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo": {
                    "Employee": {
                        "objectClass": "ramodels.mo.employee.Employee",
                        "_import_to_mo_": "false",
                        "_ldap_attributes_": [],
                        "uuid": "{{ employee_uuid or '' }}",
                    },
                    "EmailEmployee": {
                        "objectClass": "ramodels.mo.details.address.Address",
                        "_import_to_mo_": "true",
                        "_ldap_attributes_": ["carLicense", "mail"],
                        "_mapper_": "{{ obj.address_type }}",
                        # carLicense is arbitrarily chosen as an enabled/disabled marker
                        "_terminate_": "{{ now()|mo_datestring if ldap.carLicense == 'EXPIRED' else '' }}",
                        "value": "{{ ldap.mail }}",
                        "address_type": "{{ dict(uuid=get_employee_address_type_uuid('EmailEmployee')) }}",
                        "person": "{{ dict(uuid=employee_uuid ) }}",
                        "visibility": "{{ dict(uuid=get_visibility_uuid('Public')) }}",
                    },
                },
                # TODO: why is this required?
                "username_generator": {
                    "objectClass": "UserNameGenerator",
                    "combinations_to_try": ["FFFX", "LLLX"],
                },
            }
        ),
    }
)
async def test_to_mo(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    mo_person: UUID,
    ldap_connection: Connection,
    ldap_org: list[str],
    ldap_api: LDAPAPI,
) -> None:
    async def assert_address(expected: list[dict]) -> None:
        addresses = await graphql_client._testing__address_read(
            filter=AddressFilter(
                employee=EmployeeFilter(uuids=[mo_person]),
                from_date=None,
                to_date=None,
            ),
        )
        address = one(addresses.objects)
        validities = [validity.dict() for validity in address.validities]
        assert validities == expected

    person_dn = combine_dn_strings(["uid=abk"] + ldap_org)

    # LDAP: Create
    mail = "create@example.com"
    await ldap_add(
        ldap_connection,
        dn=person_dn,
        object_class=["top", "person", "organizationalPerson", "inetOrgPerson"],
        attributes={
            "objectClass": ["top", "person", "organizationalPerson", "inetOrgPerson"],
            "ou": "os2mo",
            "cn": "Aage Bach Klarskov",
            "sn": "Bach Klarskov",
            "employeeNumber": "2108613133",
            "mail": mail,
            "carLicense": "ACTIVE",
        },
    )

    # Convert LDAP person to LDAP UUID
    ldap_person_uuid = await ldap_api.get_ldap_unique_ldap_uuid(person_dn)

    # Trigger synchronization, we expect the address to be created
    with freeze_time("2022-01-01"):
        content = str(ldap_person_uuid)
        headers = {"Content-Type": "text/plain"}
        result = await test_client.post(
            "/ldap2mo/uuid", content=content, headers=headers
        )
        assert result.status_code == 200

    mo_address = {
        "uuid": ANY,
        "user_key": ANY,
        "address_type": {"user_key": "EmailEmployee"},
        "value": mail,
        "value2": None,
        "person": [{"uuid": mo_person}],
        "visibility": {"user_key": "Public"},
        # Freeze time to 2022-01-01 makes this created then
        "validity": {"from_": datetime(2022, 1, 1, tzinfo=MO_TZ), "to": None},
    }
    await assert_address([mo_address])

    # LDAP: Edit
    mail = "edit@example.com"
    await ldap_modify(
        ldap_connection,
        dn=person_dn,
        changes={
            "mail": [("MODIFY_REPLACE", mail)],
        },
    )

    # Trigger synchronization, we expect the address to be updated
    with freeze_time("2023-01-01"):
        content = str(ldap_person_uuid)
        headers = {"Content-Type": "text/plain"}
        result = await test_client.post(
            "/ldap2mo/uuid", content=content, headers=headers
        )
        assert result.status_code == 200

    expected = [
        {
            **mo_address,
            "validity": {
                **mo_address["validity"],
                # Freeze time to 2023-01-01 + edit makes this validity end just before
                "to": datetime(2022, 12, 31, tzinfo=MO_TZ),
            },
        },
        {
            # Freeze time to 2023-01-01 makes this validity start with new data then
            **mo_address,
            "validity": {"from_": datetime(2023, 1, 1, tzinfo=MO_TZ), "to": None},
            "value": mail,
        },
    ]
    await assert_address(expected)

    # LDAP: Terminate
    await ldap_modify(
        ldap_connection,
        dn=person_dn,
        changes={
            "carLicense": [("MODIFY_REPLACE", "EXPIRED")],
        },
    )

    # Trigger synchronization, we expect the address to be terminated
    with freeze_time("2024-01-01"):
        content = str(ldap_person_uuid)
        headers = {"Content-Type": "text/plain"}
        result = await test_client.post(
            "/ldap2mo/uuid", content=content, headers=headers
        )
        assert result.status_code == 200

    # Update the to date on the newest validity
    last(expected)["validity"] = {
        **last(expected)["validity"],
        # TODO: Is this sane, or should it be 2024-01-01?
        "to": mo_today(),
    }

    await assert_address(expected)
