# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Tests for the `_for_each_` mapping key.

The `_for_each_` mapping key is available to all `LDAP2MOMapping`s
(i.e. both `ldap_to_mo` and `ldap_to_mo_any`) containing a Jinja template
which if set, when evaluated should return a list, which will then in
turn be provided to the subsequent templates by looping through the
elements of the list, providing each element in the `each` contextual
variable.
"""

import json
from collections.abc import Awaitable
from collections.abc import Callable
from uuid import UUID

import pytest
from httpx import AsyncClient
from ldap3 import MODIFY_REPLACE
from more_itertools import one

from mo_ldap_import_export.autogenerated_graphql_client import EmployeeFilter
from mo_ldap_import_export.autogenerated_graphql_client import EngagementFilter
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client import (
    ReadEngagementsEngagementsObjectsValidities as EngagementValidity,
)
from mo_ldap_import_export.ldapapi import LDAPAPI
from mo_ldap_import_export.types import DN
from mo_ldap_import_export.types import LDAPUUID
from tests.integration.conftest import AddEngagement


@pytest.fixture
async def read_engagements(
    graphql_client: GraphQLClient,
    mo_person: UUID,
) -> Callable[[], Awaitable[list[EngagementValidity]]]:
    async def inner() -> list[EngagementValidity]:
        response = await graphql_client.read_engagements(
            filter=EngagementFilter(employee=EmployeeFilter(uuids=[mo_person])),
        )
        return [one(e.validities) for e in response.objects]

    return inner


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo": {
                    "Engagement": {
                        "objectClass": "Engagement",
                        "_import_to_mo_": "true",
                        "_ldap_attributes_": ["carLicense", "title"],
                        # Call load engagement on each UUID in the carLicense list,
                        # exposing the MO engagement objects as each for the mapping.
                        "_for_each_": """
                            [
                                {% for v in ldap.carLicense %}
                                    {{ load_mo_engagement(v).json() }}
                                    {% if not loop.last %},{% endif %}
                                {% endfor %}
                            ]
                        """,
                        "uuid": "{{ each.uuid }}",
                        "user_key": "{{ each.user_key }}",
                        "person": "{{ each.person }}",
                        "org_unit": "{{ each.org_unit }}",
                        "engagement_type": "{{ each.engagement_type }}",
                        "job_function": "{{ each.job_function }}",
                        "primary": "{{ each.primary }}",
                        "extension_2": "{{ ldap.title }}",
                    },
                },
            }
        ),
    }
)
async def test_for_each_iterates_carLicense(
    add_engagement: AddEngagement,
    read_engagements: Callable[[], Awaitable[list[EngagementValidity]]],
    ldap_api: LDAPAPI,
    ldap_person_dn: DN,
    trigger_ldap_person: Callable[[], Awaitable[None]],
) -> None:
    engagement_uuids = [await add_engagement(f"engagement-{i}") for i in range(3)]

    # Without carLicense, the for_each renders to an empty list,
    # and thus no engagement is updated
    await trigger_ldap_person()
    engagements = await read_engagements()
    assert {e.extension_2 for e in engagements} == {None}

    # With carLicense, every listed engagement gets extension_2 set
    await ldap_api.ldap_connection.ldap_modify(
        dn=ldap_person_dn,
        changes={
            "carLicense": [(MODIFY_REPLACE, list(map(str, engagement_uuids)))],
        },
    )
    await trigger_ldap_person()
    engagements = await read_engagements()
    assert {e.uuid for e in engagements} == set(engagement_uuids)
    assert {e.extension_2 for e in engagements} == {"Skole underviser"}


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo": {
                    "Engagement": {
                        "objectClass": "Engagement",
                        "_import_to_mo_": "true",
                        "_ldap_attributes_": ["carLicense"],
                        # Pass the carLicense field through directly
                        "_for_each_": "{{ ldap.carLicense }}",
                        "uuid": "{{ each.uuid }}",
                        "user_key": "{{ each.user_key }}",
                        "person": "{{ each.person }}",
                        "org_unit": "{{ each.org_unit }}",
                        "engagement_type": "{{ each.engagement_type }}",
                        "job_function": "{{ each.job_function }}",
                        "primary": "{{ each.primary }}",
                    },
                },
            }
        ),
    }
)
@pytest.mark.parametrize(
    "car_license, rendered_type",
    [
        ("{'x': 1}", "dict"),
        ("hello", "str"),
        ("None", "NoneType"),
    ],
)
@pytest.mark.usefixtures("mo_person")
async def test_for_each_rejects_non_list(
    test_client: AsyncClient,
    ldap_api: LDAPAPI,
    ldap_person_dn: DN,
    ldap_person_uuid: LDAPUUID,
    car_license: str,
    rendered_type: str,
) -> None:
    """`_for_each_` must render to a list."""
    await ldap_api.ldap_connection.ldap_modify(
        dn=ldap_person_dn,
        changes={"carLicense": [(MODIFY_REPLACE, [car_license])]},
    )
    response = await test_client.post(
        "/ldap2mo/uuid",
        json={"subject": str(ldap_person_uuid), "priority": 1},
    )
    assert response.status_code == 500
    detail = response.json()["detail"]
    assert "'_for_each_' template must render to a list" in detail
    assert f"got <class '{rendered_type}'>" in detail
    assert car_license in detail


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo_any": {
                    "inetOrgPerson": [
                        {
                            "objectClass": "Engagement",
                            "_import_to_mo_": "true",
                            "_ldap_attributes_": [
                                "title",
                                "entryUUID",
                                "employeeNumber",
                            ],
                            "_for_each_": """
                                {% set mo_employee = find_mo_employee_uuid_by_guid_and_cpr(
                                    ldap.entryUUID, ldap.employeeNumber
                                ) %}
                                {% set engagements = get_engagement_uuids(
                                    {"employee": {"uuids": [mo_employee]}}
                                ) %}
                                [
                                    {% for engagement in engagements %}
                                        {{ load_mo_engagement(engagement).json() }}
                                        {% if not loop.last %},{% endif %}
                                    {% endfor %}
                                ]
                            """,
                            "uuid": "{{ each.uuid }}",
                            "user_key": "{{ each.user_key }}",
                            "person": "{{ each.person }}",
                            "org_unit": "{{ each.org_unit }}",
                            "engagement_type": "{{ each.engagement_type }}",
                            "job_function": "{{ each.job_function }}",
                            "primary": "{{ each.primary }}",
                            "extension_2": "{{ ldap.title }}",
                        },
                    ],
                },
            }
        ),
    }
)
async def test_for_each_propagates_title_to_all_engagements(
    add_engagement: AddEngagement,
    read_engagements: Callable[[], Awaitable[list[EngagementValidity]]],
    trigger_ldap_person: Callable[[], Awaitable[None]],
) -> None:
    engagement_uuids = {await add_engagement(f"engagement-{i}") for i in range(3)}

    await trigger_ldap_person()

    engagements = await read_engagements()
    assert {e.uuid for e in engagements} == engagement_uuids
    assert {e.extension_2 for e in engagements} == {"Skole underviser"}
