# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from typing import Any
from collections.abc import Awaitable
from collections.abc import Callable
from datetime import datetime
from unittest.mock import ANY
from uuid import UUID
from mo_ldap_import_export.ldapapi import LDAPAPI
from mo_ldap_import_export.types import DN

import pytest
from more_itertools import one

from mo_ldap_import_export.autogenerated_graphql_client import AddressCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import AddressFilter
from mo_ldap_import_export.autogenerated_graphql_client import EmployeeFilter
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client import RAValidityInput
from mo_ldap_import_export.utils import MO_TZ


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo": {
                    "EmailEmployee": {
                        "objectClass": "Address",
                        "_import_to_mo_": "true",
                        "_ldap_attributes_": ["carLicense"],
                        # carLicense is arbitrarily chosen as our termination field
                        "_terminate_": "{{ ldap.carLicense or '' }}",
                        "uuid": "{{ get_address_uuid({'address_type': {'user_key': 'EmailEmployee'}, 'employee': {'uuids': [employee_uuid]}}) }}",
                        "user_key": "-",
                        "person": "{{ employee_uuid }}",
                        "address_type": "{{ get_employee_address_type_uuid('EmailEmployee') }}",
                        "value": "person@example.org",
                    },
                },
            }
        ),
    }
)
@pytest.mark.usefixtures("test_client")
async def test_validity_expansion(
    graphql_client: GraphQLClient,
    mo_person: UUID,
    ldap_api: LDAPAPI,
    ldap_person_dn: DN,
    trigger_ldap_person: Callable[[], Awaitable[None]],
) -> None:
    async def get_address() -> dict[str, Any]:
        addresses = await graphql_client._testing__address_read(
            filter=AddressFilter(
                employee=EmployeeFilter(uuids=[mo_person]),
                from_date=None,
                to_date=None,
            ),
        )
        address = one(addresses.objects)
        validities = one(address.validities)
        return validities.dict()

    expected = {
       'uuid': ANY,
       'user_key': '-',
       'address_type': {'user_key': 'EmailEmployee'},
       'visibility': None,
       'person': [{'uuid': mo_person}],
       'value': 'person@example.org',
       'value2': None,
       'validity': {
           'from_': ANY,
           'to': None,
       },
    }

    # Trigger and check the address was created
    await trigger_ldap_person()
    assert await get_address() == expected

    # Trigger and see that nothing changed
    await trigger_ldap_person()
    assert await get_address() == expected

    # Set a termination date
    # Then trigger and see that we can read it
    await ldap_api.ldap_connection.ldap_modify(
        dn=ldap_person_dn,
        changes={
            "carLicense": [("MODIFY_REPLACE", "4000-01-01")],
        },
    )
    await trigger_ldap_person()

    expected = {
        **expected,
        'validity': {
           'from_': ANY,
           'to': datetime(4000, 1, 1, 0, 0, tzinfo=MO_TZ),
       },
    }
    assert await get_address() == expected

    # Move termination date further into the future
    # Then trigger and see that we can read it
    await ldap_api.ldap_connection.ldap_modify(
        dn=ldap_person_dn,
        changes={
            "carLicense": [("MODIFY_REPLACE", "5000-01-01")],
        },
    )
    await trigger_ldap_person()

    expected = {
        **expected,
        'validity': {
           'from_': ANY,
           'to': datetime(5000, 1, 1, 0, 0, tzinfo=MO_TZ),
       },
    }
    assert await get_address() == expected

    # Move termination date further back
    # Then trigger and see that we can read it
    await ldap_api.ldap_connection.ldap_modify(
        dn=ldap_person_dn,
        changes={
            "carLicense": [("MODIFY_REPLACE", "3000-01-01")],
        },
    )
    await trigger_ldap_person()

    expected = {
        **expected,
        'validity': {
           'from_': ANY,
           'to': datetime(3000, 1, 1, 0, 0, tzinfo=MO_TZ),
       },
    }
    assert await get_address() == expected
