# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""LDAP change event generation using DirSync."""

import asyncio
from contextlib import AbstractAsyncContextManager
from contextlib import suppress
from typing import Self

import structlog
from fastramqpi.context import Context
from ldap3 import Connection
from sqlalchemy import LargeBinary
from sqlalchemy import Text
from sqlalchemy import Uuid
from sqlalchemy import select
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.ext.asyncio import async_sessionmaker
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column

from .autogenerated_graphql_client.client import GraphQLClient
from .config import Settings
from .database import Base
from .ldap import ldapresponse2entries
from .ldap_emit import publish_uuids
from .types import LDAPUUID
from .utils import combine_dn_strings

logger = structlog.stdlib.get_logger()


class LastRun(Base):
    """Database model tracking the last DirSync poll state per search base.

    This class stores the DirSync cookie and the set of UUIDs that were
    returned in the last poll. The cookie is the only state needed for
    DirSync to track changes - no modifyTimestamp tracking is required.
    """

    # NOTE: Tablename was changed here to force table recreation in lieu of Alembic
    __tablename__ = "last_run_dirsync"

    id: Mapped[int] = mapped_column(primary_key=True)
    search_base: Mapped[str] = mapped_column(
        Text, index=True, unique=True, nullable=False
    )
    # DirSync cookie is stored as binary data
    # This is the only state needed for DirSync - no modifyTimestamp tracking
    cookie: Mapped[bytes | None] = mapped_column(
        LargeBinary, default=None, nullable=True
    )
    uuids: Mapped[list[LDAPUUID]] = mapped_column(
        # Store UUIDs as array of UUID type
        default=list,
        nullable=False,
    )


class LDAPEventGenerator(AbstractAsyncContextManager):
    def __init__(
        self,
        sessionmaker: async_sessionmaker[AsyncSession],
        settings: Settings,
        graphql_client: GraphQLClient,
        ldap_connection: Connection,
    ) -> None:
        """Periodically poll LDAP for changes using DirSync."""
        self.sessionmaker = sessionmaker
        self.graphql_client = graphql_client
        self.settings = settings
        self.ldap_connection = ldap_connection

        self._pollers: set[asyncio.Task] = set()

    async def __aenter__(self) -> Self:
        """Start event generator."""
        # NOTE: The old tables are dropped here in lieu of Alembic
        # TODO: This code can be removed once it has been run for all customers.
        async with self.sessionmaker() as session, session.begin():
            await session.execute(text("DROP TABLE IF EXISTS last_run;"))
        async with self.sessionmaker() as session, session.begin():
            await session.execute(text("DROP TABLE IF EXISTS last_run_with_uuids;"))
        async with self.sessionmaker() as session, session.begin():
            await session.execute(text("DROP TABLE IF EXISTS last_run_gregorian;"))

        search_bases = {
            combine_dn_strings(
                [ldap_ou_to_scan_for_changes, self.settings.ldap_search_base]
            )
            for ldap_ou_to_scan_for_changes in self.settings.ldap_ous_to_search_in
        }

        self._pollers = {self.setup_poller(search_base) for search_base in search_bases}
        return self

    async def __aexit__(
        self, __exc_tpe: object, __exc_value: object, __traceback: object
    ) -> None:
        """Stop event generator."""
        # Signal all pollers to shutdown
        for poller in self._pollers:
            poller.cancel()
        # Wait for all pollers to be shutdown
        for poller in self._pollers:
            with suppress(asyncio.CancelledError):
                await poller

    async def healthcheck(self, context: dict | Context) -> bool:
        """Check if all poller tasks are still running.

        Args:
            context: The context (unused, but required by the healthcheck interface).

        Returns:
            True if all poller tasks are still running, False otherwise.
        """
        return all(not poller.done() for poller in self._pollers)

    def setup_poller(self, search_base: str) -> asyncio.Task:
        """Create and start an asyncio task that polls LDAP for changes.

        This method creates an asyncio task that continuously polls the LDAP
        server for changes using DirSync. The task runs until cancelled.

        Args:
            search_base: The LDAP search base to poll for changes.

        Returns:
            The asyncio.Task that was created.
        """

        def done_callback(future):
            # Silence CancelledErrors on shutdown
            with suppress(asyncio.CancelledError):
                # This ensures exceptions go to the terminal
                future.result()

        handle = asyncio.create_task(self._poller(search_base))
        handle.add_done_callback(done_callback)
        return handle

    async def poll(
        self,
        search_base: str,
        cookie: bytes | None = None,
    ) -> tuple[set[LDAPUUID], bytes | None]:
        """Poll the LDAP server for changes once using DirSync.

        Args:
            search_base:
                LDAP search base to look for changes in.
            cookie:
                DirSync cookie from the last poll, or None for the initial sync.
                When None, DirSync performs a full initial synchronization to
                establish the baseline state.

        Returns:
            A tuple of:
            - The set of UUIDs that have changed since the last poll.
            - The new DirSync cookie to use for the next poll.
        """
        logger.debug("Searching for changes using DirSync", search_base=search_base)

        # To improve performance and reduce noise, we only listen for changes to
        # objects with object classes that we are configured to consume.
        relevant_object_classes = {
            self.settings.ldap_object_class,
            *self.settings.conversion_mapping.ldap_to_mo_any,
        }
        object_class_filter = "".join(
            f"(objectClass={cls})" for cls in relevant_object_classes
        )

        search_filter = f"(|{object_class_filter})"

        # Attributes to fetch - we only need the unique ID field for DirSync
        # DirSync tracks changes via the cookie, not via modifyTimestamp
        attributes = [self.settings.ldap_unique_id_field]

        # Use ldap3's Microsoft DirSync extension
        # This must be done in a thread because ldap3's dir_sync is blocking
        dirsync_result = await asyncio.to_thread(
            self._run_dirsync,
            search_base,
            search_filter,
            attributes,
            cookie,
        )

        uuids, new_cookie = dirsync_result

        return uuids, new_cookie

    def _run_dirsync(
        self,
        search_base: str,
        search_filter: str,
        attributes: list[str],
        cookie: bytes | None,
    ) -> tuple[set[LDAPUUID], bytes | None]:
        """Run DirSync synchronously.

        Args:
            search_base: LDAP search base.
            search_filter: LDAP search filter.
            attributes: List of attributes to fetch.
            cookie: DirSync cookie from previous poll, or None for initial sync.

        Returns:
            Tuple of (set of UUIDs, new cookie).
        """
        # Create DirSync extension
        dirsync = self.ldap_connection.extend.microsoft.dir_sync(
            sync_base=search_base,
            sync_filter=search_filter,
            attributes=attributes,
            cookie=cookie,
        )

        # Run the DirSync loop
        # Note: dirsync.loop() populates self.ldap_connection.response
        dirsync.loop()

        # Extract UUIDs from the response
        # Note: self.ldap_connection.response is populated by dirsync.loop()
        responses = ldapresponse2entries(self.ldap_connection.response or [])

        uuids: set[LDAPUUID] = set()
        for event in responses:
            # Extract UUID
            uuid = event["attributes"].get(self.settings.ldap_unique_id_field, None)
            if uuid is None:  # pragma: no cover
                logger.warning("Got event without uuid", dn=event.get("dn"))
                continue
            uuids.add(LDAPUUID(uuid))

        # Get the new cookie for the next poll
        new_cookie = dirsync.cookie

        return uuids, new_cookie

    async def _poller(self, search_base: str) -> None:
        """Poll the LDAP server continuously every `settings.poll_time` seconds.

        Args:
            search_base:
                LDAP search base to look for changes in.
        """
        logger.info("Poller started", search_base=search_base)
        while True:
            await asyncio.shield(self._generate_events(search_base))
            # Wait for a while before running again
            await asyncio.sleep(self.settings.poll_time)

    async def _generate_events(self, search_base: str) -> None:
        """Poll LDAP for changes and publish events for any changed UUIDs.

        This method retrieves the last-run state from the database, polls LDAP
        using DirSync to find changes, and publishes events for any UUIDs that
        have changed. It then updates the database with the new cookie and UUIDs.

        Args:
            search_base: The LDAP search base to poll for changes.
        """
        # Ensure that a last-run row exists for our search_base
        # We do creates separately to support update locks in normal operation
        async with self.sessionmaker() as session, session.begin():
            last_run = await session.scalar(
                select(LastRun)
                .where(LastRun.search_base == search_base)
                .with_for_update()
            )
            last_run = last_run or LastRun(search_base=search_base)
            session.add(last_run)

        async with self.sessionmaker() as session, session.begin():
            # Get last run cookie from database for updating
            last_run = await session.scalar(
                select(LastRun)
                .where(LastRun.search_base == search_base)
                .with_for_update()
            )
            assert last_run is not None
            assert last_run.uuids is not None

            # Fetch changes since last-run and emit events for them
            # DirSync uses the cookie to track changes, not modifyTimestamp
            uuids, new_cookie = await self.poll(
                search_base, cookie=last_run.cookie
            )

            # Only send out events if either the UUIDs or the cookie have changed
            # Otherwise we will send out the same event over and over, every 'poll_time'
            # seconds effectively spamming the queue, which is a big issue if the UUID
            # that is getting spammed is stuck.
            if uuids != set(last_run.uuids) or new_cookie != last_run.cookie:
                await publish_uuids(self.settings, self.graphql_client, list(uuids))

            # Update last run cookie and uuids in database
            # Note: DirSync handles change tracking via cookies, not modifyTimestamp
            last_run.uuids = list(uuids)
            last_run.cookie = new_cookie
            session.add(last_run)
